package com.carloszaragoza.triviaapp.feature_trivia.domain.model.category_model

import androidx.compose.ui.graphics.Color
import com.carloszaragoza.triviaapp.R
data class Category(
    val title:String,
    val id:String,
    val definition:String?,
    val image:Int,
    val gradient:List<Color>
){
    companion object {
        val listCategories = listOf<Category>(

            Category(title ="General Knowledge" ,
                id="c1" ,
                definition = "Quiz about knowledge of a broad range of facts about various subjects",
                image=R.drawable.general_know,
                gradient = listOf(Color(0xff2B6D4C),Color(0xff1F9158))),
            Category(title ="Entertainment: Books",
                id="c2" ,
                definition = "Quiz about Books",
                image=R.drawable.general,
                gradient = listOf(Color(0xff4158D0),Color(0xffE0C3FC))),
            Category(title ="Entertainment: Films" ,
                id="c3" ,
                definition = "Quiz about Films ",
                image=R.drawable.films,
                gradient = listOf(Color(0xff283048),Color(0xff859398))),
            Category(title ="Entertainment: Music" ,
                id="c4" ,
                definition = "Quiz about Music",
                image=R.drawable.music,
                gradient = listOf(Color(0xff5C258D),Color(0xff4389A2))),
            Category(title ="Television" ,
                id="c6" ,
                definition = "Quiz about Tv Shows",
                image=R.drawable.television,
                gradient = listOf(Color(0xff614385),Color(0xff516395))),
            Category(title ="Entertainment: Video Games" ,
                id="c7" ,
                definition = "Quiz about Video Games",
                image=R.drawable.videogames,
                gradient = listOf(Color(0xff16222A),Color(0xff3A6073))),
            Category(title ="Entertainment: Board Games" ,
                id="c8" ,
                definition = "Quiz about Board Games",
                image=R.drawable.board_games,
                gradient = listOf(Color(0xffAA076B),Color(0xff61045F))),
            Category(title ="Science & Nature" ,
                id="c9" ,
                definition = "Quiz about Science & Nature",
                image=R.drawable.nature,
                gradient = listOf(Color(0xffE55D87),Color(0xff5FC3E4)) ),
            Category(title ="Science: Computers" ,
                id="c10" ,
                definition = "Quiz about Computers",
                image=R.drawable.computers,
                gradient = listOf(Color(0xff36175E),Color(0xff9768D1))),
            Category(title ="Science: Mathematics" ,
                id="c11" ,
                definition = "Quiz about Mathematics",
                image=R.drawable.maths,
                gradient = listOf(Color(0xffcc2b5e),Color(0xff753a88))),
            Category(title ="Mythology" ,
                id="c12" ,
                definition = "Quiz about Mythology",
                image=R.drawable.god,
                gradient = listOf(Color(0xff1488CC),Color(0xff2B32B2))),
            Category(title ="Sports" ,
                id="c13" ,
                definition = "Quiz about Sports",
                image=R.drawable.sports,
                gradient = listOf(Color(0xff168039),Color(0xff96ED89))),
            Category(title ="Geography" ,
                id="c14" ,
                definition = "Quiz about Geography",
                image=R.drawable.geography,
                gradient = listOf(Color(0xff461111),Color(0xffA13333))),
            Category(title ="History" ,
                id="c15" ,
                definition = "Quiz about History",
                image=R.drawable.history,
                gradient = listOf(Color(0xff536976),Color(0xff292E49))),
            Category(title ="Politics" ,
                id="c16" ,
                definition = "Quiz about Politics",
                image=R.drawable.politics,
                gradient = listOf(Color(0xff373B44),Color(0xff4286f4))),
            Category(title ="Art" ,
                id="c17" ,
                definition = "Quiz about Art",
                image=R.drawable.art,
                gradient = listOf(Color(0xffFF0099),Color(0xff493240))),
            Category(title ="Celebrities" ,
                id="c18" ,
                definition = "Quiz about Celebrities",
                image=R.drawable.celebrities,
                gradient = listOf(Color(0xff205375),Color(0xff607EAA))),
            Category(title ="Animals" ,
                id="c19" ,
                definition = "Quiz about Animals",
                image=R.drawable.animals,
                gradient = listOf(Color(0xff7D1935),Color(0xffFF4B2B))),
            Category(title ="Vehicles" ,
                id="c20" ,
                definition = "Quiz about Vehicles",
                image=R.drawable.vehicles,
                gradient = listOf(Color(0xffD61C4E),Color(0xffF37878))),
            Category(title ="Entertainment: Comics" ,
                id="c21" ,
                definition = "Quiz about Comics",
                image=R.drawable.comics,
                gradient = listOf(Color(0xff636363),Color(0xffa2ab58))),
            Category(title ="Entertainment: Japanese Anime & Manga" ,
                id="c22" ,
                definition = "Quiz about Japanese Anime & Manga",
                image=R.drawable.japan,
                gradient = listOf(Color(0xff168039),Color(0xff76BA99))),
            Category(title ="Entertainment: Cartoon & Animations" ,
                id="c23" ,
                definition = "Quiz about Cartoon & Animations",
                image=R.drawable.cartoon,
                gradient = listOf(Color(0xff1C3879),Color(0xff7FB5FF))),)
    }
}

